spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_rag?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: wanghui.airagproject.pojo
#日志分析
logging:
  level:
    wanghui.airagproject: debug
#    切分的文件块大小
rag:
  chunk-size: 200
  overlap: 50
